# Generated by Django 2.2.10 on 2021-11-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img_url', models.URLField(max_length=1000)),
                ('duration', models.IntegerField()),
                ('grade', models.FloatField()),
                ('type', models.CharField(max_length=100)),
                ('watch_url', models.URLField(max_length=1000, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
