# Generated by Django 2.2.10 on 2021-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='features',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='meta_description',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
