# Generated by Django 2.2.10 on 2021-11-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_auto_20211104_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
