# Generated by Django 2.2.10 on 2021-11-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20211104_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='restriction',
            field=models.CharField(default='G', max_length=100),
        ),
    ]
